### ISSUE TITLE
Auto gridz

### ISSUE THREAD

**Issue by alexdresko** [kennetek/gridfinity-rebuilt-openscad#1]
(I posted this in discord before realizing that it's probably better off as a GH issue)

I like this, but here's something that bothers me about all of the parametric options: If I know the thing I need a box for is 53mm high (or any height), how do I know how many units high (gridz) to use? I know each height unit is 7mm, but don't you have to account for the base of the bin and the lip of the bin? I want to make sure that my gridz value allows room at the top to nest another bin. 

What if your script optionally allowed specifying an item height, and whether or not room should be allowed at the top for nesting? The script could figure out how many gridz units to use. Further, the script could be instructed to either snap to a common gridz value (2, 3, 6, ...), or fit exactly to the height required by the item height value.

**Comment by kennetek** [comment]
The most recent commit implements this idea in what I think is an elegant way. The readme has the updated documentation for the new values `gridz_define`, `enable_lip`, and `enable_zsnap`.
