### ISSUE TITLE
skeletonized bins

### ISSUE THREAD

**Issue by DJDDDM** [kennetek/gridfinity-rebuilt-openscad#113]
Hey Ruudjhuu,
I would really love to develop with you together on this project.
I would much appreciate it if you could add me on discord DJDDM#6229.
I have so many ideas I will implement soon.
From a better file structure, to skeletonized bins, to flat bins who have a circle on top of them and probably most importantly, pegboard supported baseplates.
Looking forward to hear from you,
DJDDM

**Comment by Ruudjhuu** [comment]
Hi DJDDDM,

Help is always welcome. You can create pull requests which I am able to review and approve. I send a invite to you on discord so we can have a short communication line. When this colab works out maybe @kennetek could also give you review permissions so we can move this repo forward together.

@kennetek are you also interested in discord? We could setup a small server for the developers of this repo for brainstorming and quick questions.
