### ISSUE TITLE
ERROR: Parser error: syntax error in file gridfinity-rebuilt-bins.scad, line 1 

### ISSUE THREAD

**Issue by plexi32** [kennetek/gridfinity-rebuilt-openscad#123]
just opened the file (bins and lite). I immediately get that error. Any suggestions?

**Comment by kennetek** [comment]
You need to download the whole repo, the main scripts use code from other files such as gridfinity-rebuilt-utility.scad

**Comment by kennetek** [comment]
![image](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/40445044/23b11481-27ec-4997-904f-4f368e311d04)
Download the zip file of the whole repository, then extract somewhere. Then open your desired files in OpenSCAD

**Comment by plexi32** [comment]
perfect, thx for your help, now it works smootthly!
