### ISSUE TITLE
50mm grid issues

### ISSUE THREAD

**Issue by peter-banks** [kennetek/gridfinity-rebuilt-openscad#13]
Thanks so much for this project, its exactly what ive been looking for, however ive got a couple minor issues with the dimensions when I'm running at 50mm grid x/y/z size. I'm using the original frames scaled to 50mm increments and the original divider boxes scaled to the same work fine.

1. The radius of the base where it sits in the grid is slightly too "square", once I filed it down a bit it fits well. I tried playing with the parameters but couldn't quite find the right one.
2. The lip with the tab is about 1mm too high and means they dont stack as well together.
3. If i set `length = 50` the base is slightly too big as is the lip opening so they dont stack as nicely, if I set to 49 everything fits well. This workaround is fine for my needs but just mentioning it anyway.

Attached the customerize config
![customizer config](https://user-images.githubusercontent.com/15824945/192528322-7ad84088-31f5-4e57-84f2-0d1713b3b01f.png)

**Comment by unteins** [comment]
Assuming that the 42 mm bins ARE perfectly the same as the original, it would probably make the most sense to simply make a bin at 42 mm grid size and scale it up to 50 mm as you do with other bins. This should solve all of the small quirks from trying to make them natively at 50 mm.

**Comment by peter-banks** [comment]
Thank you @kennetek and @unteins. 

@kennetek Yeah sorry i meant Zack's bins and frames from Thangs.
Both solutions technically work and perfectly usable for my purpose however changing the length (as you mentioned) does seem to affect the hole placement and size (see the photo below, bin marked K). I think using @unteins idea keeps it scaled properly and less likely to hit other issues so probably the safest option in this case.

Attaching my openscad config for reference
![image](https://user-images.githubusercontent.com/15824945/192901947-222396e6-0211-4838-8a4a-1223c839c71f.png)
![IMG_20220929_083055](https://user-images.githubusercontent.com/15824945/192901889-abb7b274-c9c5-4d80-851e-dbaaf23775b1.jpg)
