### ISSUE TITLE
Default values of gridfinity-rebuilt-bins (in particular height_internal = 0) produce filled bin with no tab

### ISSUE THREAD

**Issue by JacquesOpaux** [kennetek/gridfinity-rebuilt-openscad#152]
I'm afraid I'm missing something very obvious, but gridfinity-rebuilt-bins does not seem to work as intended. More specifically :
    - setting height_internal = 0 results in a "full" bin
    - I cannot get tabs

To check that it is not specific to my installation, I downloaded the latest stable version of openscad, the current gridfinity-rebuilt repository, opened gridfinity-rebuilt-bins.scad and rendered with default values. This produced the picture below.
![default_bin](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/157601653/b285c517-37e3-468d-944a-b17823eca284)
I also checked on another computer with the same result.

An older version of gridfinity-rebuilt works as intended.

For what is worth, a negative value for height_internal does produce some depth in the bin.

**Comment by colde** [comment]
Setting the divx and divy to 1 should get you what you are looking for. The default is no compartments, but divx and divy controls the number of compartments.

<img width="602" alt="PrivatScreenShot 2024-01-26 at 00 00 48" src="https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1199413/2d0fb66f-0689-4f67-a070-059af9e31a80">

This the place to adjust it if using the customizer.

**Comment by JacquesOpaux** [comment]
Thank you very much for taking the time. And indeed, I was missing something very obvious...
