### ISSUE TITLE
Skeletonized baseplate with magnets is broken

### ISSUE THREAD

**Issue by evranch** [kennetek/gridfinity-rebuilt-openscad#163]
Running OpenSCAD 2024.01.26.ai18259 (latest AppImage) and latest version of this repo as of Jan 28.
Using fast-csg and Manifold libraries to render, but this issue happens in both preview and in render.

Style "skeletonized" will only generate properly if you uncheck magnet holes and set hole style to "none".
Otherwise, I just get the regular "weighted" baseplate.

No errors are generated and rendering works fine, it just isn't skeletonized. 
Edit: the preview shows the skeletonized baseplate with magnet holes unchecked, but rendering still generates a solid bottom.

Unfortunately I have zero skills with OpenSCAD to debug it, I only know how to use standard parametric CAD software.

**Comment by jpypi** [comment]
Have you tried this since 36345f3 (current main)? I was having this issue as well, but it seems to be resolved now.

**Comment by evranch** [comment]
Just tested it - working now, thanks
