### ISSUE TITLE
Superfluous internal walls

### ISSUE THREAD

**Issue by salzk** [kennetek/gridfinity-rebuilt-openscad#2]
In the 3x3 example if I cut a wide compartment with 
      cut(x=0,y=0,w=3,h=1,t=5,s=false);
I get two 1.5 wide compartments rather than just one.

**Comment by kennetek** [comment]
Can you post the full code snippet that you are using to generate the bin?

**Comment by salzk** [comment]
Sorry Kenneth, my fault. I added a gridfinityCustom function at the end (as per the examples) and overlooked line 47. Once I commented it out, everything was fine. Thanks for your excellent work!
