### ISSUE TITLE
Skeletonized styles are not working anymore

### ISSUE THREAD

**Issue by freiser77** [kennetek/gridfinity-rebuilt-openscad#202]
Hello,

I want to generate a 4x3 baseplate in the skeletonized style with magnet holes and screw together possibility.
<img width="531" alt="Bildschirmfoto 2024-07-10 um 11 53 10" src="https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/14125584/fb8cfdb6-095f-4439-9fb7-c5cce8a9a922">

But the skeleton does not work. The inside is stilled filled and so it is not possible to screw the baseplates together.
<img width="813" alt="Bildschirmfoto 2024-07-10 um 11 53 33" src="https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/14125584/2428159f-543d-4b3c-b557-eb13aab029ea">

If I disable the magnet hole and the vertical screw holes, it works.
Is there a bug?

Greetings

Florian

**Comment by EmperorArthur** [comment]
Fixed by #187, which has been awaiting merge since May 17th.

**Comment by jhoblitt** [comment]
As #187 was merged, can this issue be closed?
