### ISSUE TITLE
[Vase Mode] Grid Base Holes Have Weird Geometry

### ISSUE THREAD

**Issue by Splarkszter** [kennetek/gridfinity-rebuilt-openscad#212]
## Enabling holes leaves weird geometry
OpenSCAD Nightly 2024.07.22

![image](https://github.com/user-attachments/assets/b285cc80-ab25-4c26-b476-c4102a67d3dd)

![image](https://github.com/user-attachments/assets/4a6090cd-55cb-4288-ad48-acc7ff3031b0)

![image](https://github.com/user-attachments/assets/3b4c1d80-5c0e-4650-bef9-845159fb2af4)

**Comment by Splarkszter** [comment]
Cross section thing also seems to be flying by at least 2 layers dunno if that's intended tho:

![image](https://github.com/user-attachments/assets/c5ef1970-4b2f-4917-8388-997298de3a34)

**Comment by EmperorArthur** [comment]
Just a hunch, but I'll bet it's related to those warnings.  I need to add a ton more asserts to module definitions.  That way we won't generate bad geometry.
