### ISSUE TITLE
Bug: Interior corners have spurious geometry making models unsolid

### ISSUE THREAD

**Issue by aderusha** [kennetek/gridfinity-rebuilt-openscad#242]
![bad_geometry](https://github.com/user-attachments/assets/e3d7ebd9-fac5-49d9-8afa-88d37f2e21a6)
Shown here with the bone stock code as downloaded from the repo, all of my bins now are coming out unsolid due in large part to this weird geometry that's now being generated around every bottom corner.  There are also gaps in the mesh near the bottom.

**Comment by EmperorArthur** [comment]
I have a fix for this and the issues with lite bases, and will be making a Pull Request shortly.

From a technical standpoint, it has something to do with the radius passed into the rounded square function.  Either that or the way OpenSCAD creates circles is preventing meshing.  I have fixed this by adjusting the method used to create the profile so a simple cube can be used instead.
