### ISSUE TITLE
Error on render after commit a13f526

### ISSUE THREAD

**Issue by stefanofcosta** [kennetek/gridfinity-rebuilt-openscad#246]
The commit a13f526 is the last one running, if you download any version after this commit, you can find the following errors:

In CGAL:
![image](https://github.com/user-attachments/assets/4c30ebc3-aa44-46fa-ad9e-fec538514e82)

In Manifold:
![image](https://github.com/user-attachments/assets/5c3fa769-0c33-47e6-a276-44b01b552fa7)

Tested in Windows 11, Ubuntu 24.04 and MacOS Sequoia 15.1

Tested in OpenSCAD 2021.01, 2024.11.03, 2024.11.08

**Comment by faokryn** [comment]
I also appear to be experiencing this issue with gridfinity-rebuilt-baseplate.scad:

![2024-11-21_105642-0500](https://github.com/user-attachments/assets/bfef9bd7-00f1-4798-80e7-f92097e74b44)

I confirmed the issue does not appear in a13f526, but I worked my way forward from there and seem to be rendering correctly as late as 1ee99f9, d47043f being the first commit where the error appears - which seems to coincide with the commit message: "Updated solid base creation logic".

OS: Fedora 38
OpenSCAD version: 2021.01
