### ISSUE TITLE
Thin Style Baseplates Not Rendering Properly

### ISSUE THREAD

**Issue by buildxyz-git** [kennetek/gridfinity-rebuilt-openscad#252]
Excellent project!

I wanted to make a simple thin frame but even just setting this with no other option set gives me odd rendering results:
```
// baseplate styles
style_plate = 0; // [0: thin, 1:weighted, 2:skeletonized, 3: screw together, 4: screw together minimal]
```

for example, a 2x2 grid previews as:
![Screenshot 2024-11-21 at 9 03 12 AM](https://github.com/user-attachments/assets/9d137132-fe3e-4057-b496-925c9b72c6f5)

but renders as:
![Screenshot 2024-11-21 at 9 03 36 AM](https://github.com/user-attachments/assets/7eb2349b-da8b-41f2-9f83-20ef34a079ea)

Am I messing something up here?

**Comment by wjugit** [comment]
I ran into a similar issue.  Resolved it locally by _uncommenting_ the final [0,0] entry in the definition of BASEPLATE_LIP in src/core/standard.scad (see below).   This may also fix #246 and #247.   

BASEPLATE_LIP = [
    [0, 0], // Innermost bottom point
    [0.7, 0.7], // Up and out at a 45 degree angle
    [0.7, (0.7+1.8)], // Straight up
    [(0.7+2.15), (0.7+1.8+2.15)], // Up and out at a 45 degree angle
    [(0.7+2.15), 0], // Straight down
    **[0, 0] // Implicit back to start**
];

**Comment by buildxyz-git** [comment]
Yep, that fixed it thank you!

**Comment by madhephaestus** [comment]
I made the suggested change in a PR, I hope its merged soon :) I just added this project to [CaDoodle](https://github.com/CommonWealthRobotics/CaDoodle/blob/main/README.md) as a shape generator.
