### ISSUE TITLE
Vase mode - nozzle size (description)

### ISSUE THREAD

**Issue by merlin-world** [kennetek/gridfinity-rebuilt-openscad#27]
Does the **nozzle** parameter refer to extrusion width? For instance, if I use 0.4 nozzle with over-extrusion at 0.6 mm, what to put in this parameter?

**Comment by kennetek** [comment]
Yes. Because the walls are 2 perimeters thick, I needed an input to know how large to make the walls in the model. Nozzle size is an incorrect metric, extrusion width is the more appropriate value. It was for easier accessibility, I will add a note for the parameter description.
