### ISSUE TITLE
Baseplate w/ Magnet Holes - No Complex Screw Hole Geometry

### ISSUE THREAD

**Issue by mcdviii** [kennetek/gridfinity-rebuilt-openscad#44]
I'm trying to diagnose why the base plate script doesn't render the screw hole geometry (for magnet holes). 'Enable Magnet Holes' is checked, and I've tried all appropriate base plate styles. Both the preview & rendered geometry show only the pocket for the magnet.

This is important to me because I want the option of using a glue-up jig.

OpenSCAD version 2022.12.28.ai13153 (git 8f7dd26fc)

**Comment by kennetek** [comment]
My bad, in one of the most recent commits, the style_hole parameter was deleted. I don't know why that happened. I put it back, hopefully that fixes the problem

**Comment by mcdviii** [comment]
Beautiful! Issue resolved. Thank you for your attention on this.

On December 31, 2022 12:36:59 AM CST, Kenneth ***@***.***> wrote:
>My bad, in one of the most recent commits, the style_hole parameter was deleted. I don't know why that happened. I put it back, hopefully that fixes the problem
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/kennetek/gridfinity-rebuilt-openscad/issues/44#issuecomment-1368173643
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
