### ISSUE TITLE
"mesh not closed" in stl when using default style_lip=0

### ISSUE THREAD

**Issue by 61a58e50be** [kennetek/gridfinity-rebuilt-openscad#65]
I noticed some inconsistencies when working with `stl`s generated by this lib. I was able to trace the cause back to the default `style_lip=0`. The problem does not appear when `style_lip=1` is used.

Steps to reproduce:
1. render the default `gridfinity-rebuilt-bins.scad` from main branch - save as `gridfinity-rebuilt-bins-default.stl`
2. only change `style_lip=1` - render & save as `gridfinity-rebuilt-bins-style_lip_1.stl`
3. use the minimal working sample code below to trigger either the error `ERROR: The given mesh is not closed! Unable to convert to CGAL_Nef_Polyhedron. ` and/or don't get any output in openscad's 3d viewer.

working as expected:
```
difference(){
    import("./gridfinity-rebuilt-bins-style_lip_1.stl");
    cube([25,25,100], center=true);
}
```
![image](https://user-images.githubusercontent.com/10894392/218177745-35851f6a-1886-4ae3-bbf7-407d95dbbe38.png)

does not work:
```
difference(){
    import("./gridfinity-rebuilt-bins-default.stl");
    cube([25,25,100], center=true);
}
```
![image](https://user-images.githubusercontent.com/10894392/218178231-0561812b-2549-4ef4-9d1f-3c50394e15e7.png)

**Comment by kennetek** [comment]
Interesting, I cannot replicate this error. I am using 2022.11.13.ci12787, a development snapshot with fast-csg enabled. I guess it must not work properly in the stable release of OpenSCAD. I honestly do not know how to fix that.
