### ISSUE TITLE
Wrong location for magnet holes in bases?

### ISSUE THREAD

**Issue by cseelye** [kennetek/gridfinity-rebuilt-openscad#77]
I'm seeing the magnet holes in the bases are getting cut into the center of each grid instead of in the four corners. Took me  a minute to figure out why I didn't see any difference with magnets enabled/disabled, but when I change the style to the full weighted baseplate I can see the holes appear and disappear. I'm running a fresh clone of the repo.
![screen](https://user-images.githubusercontent.com/15304724/220961075-a5cc49ba-392d-401a-9896-30282c22839c.png)

**Comment by Ruudjhuu** [comment]
You are correct, I provide a fix in #72. If you want to use this branch as a temporary workaround, watch out with using any of the screw together types as they are not final yet.

**Comment by cseelye** [comment]
Awesome, thanks for the quick reply!

**Comment by cseelye** [comment]
Thanks for your efforts on this, this project is fantastic and I use it all the time!
