### ISSUE TITLE
"Only cut magnet/screw holes at corners" doesn't work

### ISSUE THREAD

**Issue by dwineman** [kennetek/gridfinity-rebuilt-openscad#88]
It seems to just suppress the holes entirely. (OpenSCAD 2023.03.17 snapshot.) I love the idea though...

**Comment by Ruudjhuu** [comment]
You are right, I think I broke this feature in 0538b37c3db182e96a2ad5990dada304cd1926d7. You can use the repo before this commit if you really need it while I'll work on a fix.
